[2025-01-17T20:52:01.841+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-17T20:52:01.859+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spaceflight_data_ingest_v2.fetch_events manual__2025-01-17T20:51:57.103152+00:00 [queued]>
[2025-01-17T20:52:01.866+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spaceflight_data_ingest_v2.fetch_events manual__2025-01-17T20:51:57.103152+00:00 [queued]>
[2025-01-17T20:52:01.866+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-17T20:52:01.882+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_events> on 2025-01-17 20:51:57.103152+00:00
[2025-01-17T20:52:01.892+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=697) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-17T20:52:01.893+0000] {standard_task_runner.py:72} INFO - Started process 699 to run task
[2025-01-17T20:52:01.893+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spaceflight_data_ingest_v2', 'fetch_events', 'manual__2025-01-17T20:51:57.103152+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/spaceflight_data_ingest_v2.py', '--cfg-path', '/tmp/tmppkg7sod5']
[2025-01-17T20:52:01.894+0000] {standard_task_runner.py:105} INFO - Job 70: Subtask fetch_events
[2025-01-17T20:52:01.944+0000] {task_command.py:467} INFO - Running <TaskInstance: spaceflight_data_ingest_v2.fetch_events manual__2025-01-17T20:51:57.103152+00:00 [running]> on host 59ff16f1d4fb
[2025-01-17T20:52:02.041+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spaceflight_data_ingest_v2' AIRFLOW_CTX_TASK_ID='fetch_events' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T20:51:57.103152+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T20:51:57.103152+00:00'
[2025-01-17T20:52:02.042+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-17T20:52:02.042+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-17T20:52:02.043+0000] {logging_mixin.py:190} INFO - Current task name:fetch_events state:running start_date:2025-01-17 20:52:01.859650+00:00
[2025-01-17T20:52:02.043+0000] {logging_mixin.py:190} INFO - Dag name:spaceflight_data_ingest_v2 and current dag run status:running
[2025-01-17T20:52:02.043+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-17T20:52:02.305+0000] {spaceflight_data_ingest_v2.py:112} ERROR - Error al obtener eventos: 404
[2025-01-17T20:52:02.305+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-17T20:52:02.316+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-17T20:52:02.316+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=spaceflight_data_ingest_v2, task_id=fetch_events, run_id=manual__2025-01-17T20:51:57.103152+00:00, execution_date=20250117T205157, start_date=20250117T205201, end_date=20250117T205202
[2025-01-17T20:52:02.327+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-17T20:52:02.328+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-17T20:52:02.328+0000] {logging_mixin.py:190} INFO - Dag name:spaceflight_data_ingest_v2 queued_at:2025-01-17 20:51:57.124973+00:00
[2025-01-17T20:52:02.328+0000] {logging_mixin.py:190} INFO - Task hostname:59ff16f1d4fb operator:PythonOperator
[2025-01-17T20:52:02.357+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-17T20:52:02.377+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-17T20:52:02.381+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
