[2025-01-19T04:15:20.252+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-19T04:15:20.279+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spaceflight_data_ingest_v2.fetch_events manual__2025-01-17T22:00:09.158485+00:00 [queued]>
[2025-01-19T04:15:20.293+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spaceflight_data_ingest_v2.fetch_events manual__2025-01-17T22:00:09.158485+00:00 [queued]>
[2025-01-19T04:15:20.294+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-19T04:15:20.320+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_events> on 2025-01-17 22:00:09.158485+00:00
[2025-01-19T04:15:20.332+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=238) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-19T04:15:20.333+0000] {standard_task_runner.py:72} INFO - Started process 247 to run task
[2025-01-19T04:15:20.334+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spaceflight_data_ingest_v2', 'fetch_events', 'manual__2025-01-17T22:00:09.158485+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/spaceflight_data_ingest_v2.py', '--cfg-path', '/tmp/tmpysu3n7mr']
[2025-01-19T04:15:20.336+0000] {standard_task_runner.py:105} INFO - Job 143: Subtask fetch_events
[2025-01-19T04:15:20.396+0000] {task_command.py:467} INFO - Running <TaskInstance: spaceflight_data_ingest_v2.fetch_events manual__2025-01-17T22:00:09.158485+00:00 [running]> on host 59ff16f1d4fb
[2025-01-19T04:15:20.797+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spaceflight_data_ingest_v2' AIRFLOW_CTX_TASK_ID='fetch_events' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T22:00:09.158485+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T22:00:09.158485+00:00'
[2025-01-19T04:15:20.797+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-19T04:15:20.798+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-19T04:15:20.798+0000] {logging_mixin.py:190} INFO - Current task name:fetch_events state:running start_date:2025-01-19 04:15:20.280121+00:00
[2025-01-19T04:15:20.798+0000] {logging_mixin.py:190} INFO - Dag name:spaceflight_data_ingest_v2 and current dag run status:running
[2025-01-19T04:15:20.798+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-19T04:15:20.984+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:16:17.379+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:17:13.468+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:18:09.730+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:19:06.015+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:20:02.346+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:20:57.774+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:21:54.049+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:22:50.170+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:23:46.218+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:24:42.206+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:25:38.248+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:26:34.170+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:27:30.176+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:28:26.108+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:29:22.082+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:30:17.676+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:31:13.314+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:32:09.034+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:33:04.394+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:34:00.032+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:34:55.558+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:35:51.036+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:36:46.857+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:37:42.431+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:38:37.993+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:39:33.397+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:40:29.048+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:41:24.781+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:42:20.016+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:43:15.491+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:44:10.845+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:45:06.033+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:46:01.334+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:46:56.602+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:47:51.892+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:48:47.177+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:49:42.360+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:50:37.492+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:51:32.710+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:52:27.666+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:53:22.689+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:54:17.999+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:55:13.084+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:56:08.163+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:57:03.312+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:57:58.407+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:58:53.469+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T04:59:48.579+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:00:43.608+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:01:38.787+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:02:33.876+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:03:28.804+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:04:23.876+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:05:19.161+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:06:14.113+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:07:09.104+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:08:04.036+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:08:59.004+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:09:54.067+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:10:48.219+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:11:41.327+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:12:36.068+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:13:30.968+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:14:25.952+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:15:20.849+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:16:15.660+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:17:10.724+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:18:05.613+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:19:00.511+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:19:56.578+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:20:51.505+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:21:46.428+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:22:41.342+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:23:36.092+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:24:30.979+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:25:25.732+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:26:20.424+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:27:15.508+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:28:10.323+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:29:05.251+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:30:00.266+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:30:55.092+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:31:50.084+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:32:44.907+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:33:39.787+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:34:34.705+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:35:29.549+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:36:24.439+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:37:19.265+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:38:14.193+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:39:09.109+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:40:04.052+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:40:59.267+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:41:54.203+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:42:49.106+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:43:44.134+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:44:39.019+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:45:33.927+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:46:28.804+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T05:47:23.693+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T12:39:38.005+0000] {spaceflight_data_ingest_v2.py:74} ERROR - Error al obtener events: 404
[2025-01-19T12:39:38.578+0000] {job.py:229} INFO - Heartbeat recovered after 24683.25 seconds
[2025-01-19T12:39:43.714+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2025-01-19T12:39:43.715+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-19T12:39:43.734+0000] {process_utils.py:132} INFO - Sending 15 to group 247. PIDs of all processes in the group: [247]
[2025-01-19T12:39:43.736+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 247
[2025-01-19T12:39:43.745+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-19T12:39:43.949+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/spaceflight_data_ingest_v2.py", line 95, in fetch_events
    fetch_data(
  File "/opt/airflow/dags/spaceflight_data_ingest_v2.py", line 75, in fetch_data
    time.sleep(60)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-01-19T12:39:44.001+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-19T12:39:44.002+0000] {logging_mixin.py:190} INFO - Task start:2025-01-19 04:15:20.280121+00:00 end:2025-01-19 12:39:43.983057+00:00 duration:30263.702936
[2025-01-19T12:39:44.005+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_events> dag:<DAG: spaceflight_data_ingest_v2> dagrun:<DagRun spaceflight_data_ingest_v2 @ 2025-01-17 22:00:09.158485+00:00: manual__2025-01-17T22:00:09.158485+00:00, state:running, queued_at: 2025-01-17 22:00:09.177258+00:00. externally triggered: True>
[2025-01-19T12:39:44.006+0000] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2025-01-19T12:39:44.007+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=spaceflight_data_ingest_v2, task_id=fetch_events, run_id=manual__2025-01-17T22:00:09.158485+00:00, execution_date=20250117T220009, start_date=20250119T041520, end_date=20250119T123943
[2025-01-19T12:39:44.171+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-19T12:39:44.278+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=247, status='terminated', exitcode=2, started='04:15:19') (247) terminated with exit code 2
